### ISSUE TITLE
[Bug]: FastPair: Not finding any Devices, No Tracking of devices possible 

### ISSUE THREAD

**Issue by TekkertheChaot** [Project-Elixir/issue_tracker#32]
### Issue type

Other

### Exact version and Build date

V4.1 | UQ1A.240205.004

### Bug Description

FastPair is a Connection initiation feature for Android, similar to Apples "setup nearby device" by just e.g. flipping open the airpods case. Last working state was in ElixirOS 3.13 as to my knowledge.
Because devices can not be added via FastPair, features like "Find my Device", "Call device" and "Last known location" for those devices do not work.

### Steps to Reproduce

Step 1: have a FastPair-enabled device (like earbuds). I used JBL TUNE 125TWS.
Step 2: unlock your phone.
Step 2: trigger the devices fastpair mode (most of the time it is the same as the "bluetooth detectable" mode).
Result: Normally you should get a pop up message, that a new device is detected. This does not happen in this case

### Relevant Log

```shell
See logcat in additional context
```

### Screenshots or Videos

See video with syncronized logcat timestamps in additional context

### Solution

no known solution on my side

### Additional Context

Logs and video of reproducing are available on my cloud (due to github filesize limits): https://cloud.jjmn.de/s/3TTMnHi5LCgJfqg
video has timestamps synced to the logcat.

Device: fajita (OnePlus 6T)
Rooted: false
Magisk modules: none
Build: UQ1A.240205.004
Kernel: built-in kernel
Third-Party Mods: none

### Acknowledgements

- [X] I have checked that the device is officially supported (for device specific reports and not source related).
- [X] I am running the latest version available on projectelixiros.com for this device.
- [X] I have searched the existing issues and this is a new issue and not a duplicate of any another open issue.
- [X] I have written a short but informative title.
- [X] I have filled out all of the requested information in this issue properly.

**Comment by manidweep** [comment]
device side issues, report to your maintainer
